### ISSUE TITLE
bump to 1.0; publish

### ISSUE THREAD

**Issue by lunelson** [lunelson/sass-calc#3]
- [ ] version bump
- [ ] publish to npm, bower
- [ ] fix travis CI

**Comment by lunelson** [comment]
@matthias-t I believe since your PR is merged now, this is the last current issue; I noticed you set up NPM, Travis, badges etc. on your "sass-pass" repo: would you be interested in doing the same here?

Also, if you are interested in testing, I have another repo which I don't quite know how to test...we should talk about it

**Comment by matthias-t** [comment]
Hi @lunelson!
Sure, I'll do that and drop another PR once I've rebased the one that's still open. About your other repo, I'm open to talk about it.
